name: controle_estoque_amostras_app
description: A new Flutter project.

version: 1.0.1+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  collection: ^1.17.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  diacritic: ^0.1.4
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  http: ^1.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  mask_text_input_formatter: ^2.5.0
  path: ^1.8.3
  path_provider: ^2.0.15
  responsive_sizer: ^3.1.1
  searchfield: ^0.8.3
  sqflite: ^2.2.8+4
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  lint: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kabel
      fonts:
        - asset: assets/fonts/kabel.ttf
    - family: Koblenz
      fonts:
        - asset: assets/fonts/koblenz-serial-light.otf
    - family: Futura
      fonts:
        - asset: assets/fonts/futura.ttf
    - family: Futura2
      fonts:
        - asset: assets/fonts/futura2.ttf
    - family: Lexend
      fonts:
        - asset: assets/fonts/lexend.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  adaptive_icon_background: "assets/icon/ic_launcher_adaptive_back.png"
  adaptive_icon_foreground: "assets/icon/ic_launcher_adaptive_fore.png"
  min_sdk_android: 18

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
